### ISSUE TITLE
issue with t7

### ISSUE THREAD

**Issue by LoudStank** [Draakoor/codptero#1]
gettings these errors on start up then servers crashes. 
![Screenshot 2024-05-13 233349](https://github.com/Draakoor/codptero/assets/143573943/6b3e9fd6-f8f6-4e44-9a72-6344c4ede157)

any help would be greatly appreciated.

**Comment by Draakoor** [comment]
Where is the problem? Server seems to bee runing

**Comment by LoudStank** [comment]
it auto crashing on start

**Comment by Draakoor** [comment]
Did you update the egg as told above? I dont support boiii anymore update your egg and switch to t7x

**Comment by LoudStank** [comment]
i did switch to t7x hence why im here asking for help

**Comment by Draakoor** [comment]
You attached no screenshot, so I cant help you
