### ISSUE TITLE
Issue with T6

### ISSUE THREAD

**Issue by hammyexe** [Draakoor/codptero#2]
When I start the server i get the following error and server stops:

 /entrypoint.sh: line 10: bin/plutonium-bootstrapper-win32.exe: No such file or directory

**Comment by Draakoor** [comment]
Please give me more details, I cant work with that. All eggs are runing on my machines fine.

**Comment by hammyexe** [comment]
> Please give me more details, I cant work with that. All eggs are runing on my machines fine.

what details would you like; i'm running ubuntu with an amd cpu. I'm also running the wings on a docker image.

**Comment by Draakoor** [comment]
Download the updated egg and try again

**Comment by hammyexe** [comment]
Unfortunetly I got the same error again nothing changed.

**Comment by Draakoor** [comment]
download the update and try again

**Comment by hammyexe** [comment]
> download the update and try again

Nice it worked completely fine, so what's the difference between the images?

**Comment by Draakoor** [comment]
Nothing mine is based on garrycrafts, but you can still use garrys as long as it is available
